### ISSUE TITLE
Circle-CI tests take way too long (25+ minutes)

### ISSUE THREAD

**Issue by ObjectiveTruth** [ObjectiveTruth/UoitDCLibraryBooking#2]
Linked to the use of the `avd` software emulator.

Found here

https://github.com/ObjectiveTruth/UoitDCLibraryBooking/blob/beta/circle.yml#L17-L19

```
test:
  override:
    # Run unit tests first (results will be collected at the last step)
    - ./gradlew test -PdisablePreDex
    # start the emulator
    - emulator -avd circleci-android22 -no-audio -no-window:
        background: true
        parallel: true
    # wait for it to have booted
    - circle-android wait-for-boot
    # unlock the emulator screen
    - sleep 30
    - adb shell input keyevent 82
```
